name: CI Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          sudo apt-get install mingw-w64
      - name: Build Linux
        run: |
          xmake f -m release -p linux -a x86_64
          xmake
          xmake f -m release -p linux -a aarch64
          xmake
          xmake f -m release -p linux -a armv7a
          xmake
      - name: Build Windows
        run: |
          xmake f -m release -p windows -a x86 -y
          xmake
          xmake f -m release -p windows -a x64 -y
          xmake
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            build
