name: CI Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt install squashfs-tools
          curl -L http://enclose.io/rubyc/rubyc-linux-x64.gz | gunzip > rubyc
          chmod +x rubyc
          ./rubyc --help
      - name: Install deps
        run: |
          sudo gem install bundler
          sudo bundler install
      - name: Build Linux
        run: ./rubyc -oskfantasy skfantasy.rb
      - name: Build Windows
        run: ./rubyc -oskfantasy.exe skfantasy.rb
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            skfantasy
            skfantasy.exe
