name: CI Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ubuntu-deploy
      - name: Install Mingw
        run: |
          sudo apt-get install mingw-w64
      - name: Build Linux
        run: |
          xmake f -m release -p linux -a x86_64
          xmake
      - name: Deploy Linux to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/linux/x86_64/release
          VERSION_FILE: version.txt
      - name: Build Windows
        run: |
          xmake f -m release -p windows -a x86 -y
          xmake
      - name: Deploy Windows to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/windows/x86/release
          VERSION_FILE: version.txt
