name: CI Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: ./install-deps.sh
      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
      - name: Build Linux
        run: |
          xmake f
          xmake
      - name: Build Windows
        run: |
          xmake f -p mingw
          xmake
      - name: Deploy Linux to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/linux/x86_64/release
      - name: Deploy Windows to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/windows/x86_64/release
