name: CI Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: ./install-deps.sh
      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
      - name: Build Linux
        run: |
          xmake f -p linux -a x86_64
          xmake
          xmake f -p linux -a i686
          xmake
          xmake f -p linux -a armv7a
          xmake
      - name: Build Windows
        run: |
          xmake f -p mingw -a x86_64 -y
          xmake
          xmake f -p mingw -a i686 -y
          xmake
      - name: Deploy Linux x86_64 to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux-x86_64
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/linux/x86_64/release
      - name: Deploy Linux i686 to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux-i686
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/linux/i686/release
      - name: Deploy Linux Armv7a to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux-armv7a
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/linux/armv7a/release
      - name: Deploy Windows x86_64 to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows-x86_64
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/mingw/x86_64/release
      - name: Deploy Windows i686 to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows-i686
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: build/mingw/i686/release
