name: CI Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ubuntu-deploy
      - name: Install Mingw
        run: |
          sudo update-alternatives --config x86_64-w64-mingw32-g++
          sudo apt-get install mingw-w64
          sudo update-alternatives --config x86_64-w64-mingw32-g++
      - name: Build Linux
        run: |
          xmake f -m release -p linux -a x86_64
          xmake
      - name: Build Windows
        run: |
          xmake f -m release -p mingw -a x86_64 -y
          xmake
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            build
