name: skill-fantasy-main-workflow
on:
  push:
    branch: [master]

jobs:
  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - run: xmake -y
      - run: zip skfantasy.zip build/linux/x86_64/release/skfantasy
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux-x86-64-demo
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: skfantasy.zip

  deploy-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - run: xmake -y
      - run: 7z a -tZip skfantasy.zip pdcurses.dll build/windows/x64/release/skfantasy.exe
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows-x64-demo
          ITCH_GAME: skill-fantasy
          ITCH_USER: rafael-dev-21
          PACKAGE: skfantasy.zip
